routes/web.php
        Route::get('tourDelete/{emp_id}/{token}/{action}','TourPlanningController@tourDelete');
        Route::get('tourDetails/{emp_id}/{token}','TourPlanningController@tourDetails');
        Route::post('tourApprove','TourPlanningController@tourApprove')->name('tour.approve');
        Route::post('tourReject','TourPlanningController@tourReject')->name('tour.reject');
        Route::post('tourUpdate','TourPlanningController@tourUpdate')->name('tour.update');
        Route::get('tourEdit/{tour_id}','TourPlanningController@tourEdit');

    //Demo Plan
        Route::get('getWebPendingDemoList','DemoPlanController@getWebPendingDemoList')->name('pendingDemo');
        Route::get('pendingDemoDetails/{emp_id}/{token}','DemoPlanController@pendingDemoDetails');
        Route::get('getAllDemoDetails/{emp_id}/{token}','DemoPlanController@getAllDemoDetails');
        Route::post('demoApprove','DemoPlanController@demoApprove')->name('demo.approve');
        Route::post('demoReject','DemoPlanController@demoReject')->name('demo.reject');
        Route::get('approvedDemo','DemoPlanController@getWebApprovedDemoList')->name('approvedDemos');
        Route::get('demoPrint/{emp_id}/{token}','DemoPlanController@demoPrint');
        Route::get('demoPlanExcel/{emp_id}/{token}','DemoPlanController@excel');

    //Feedback Reports
        Route::get('getDemoFeedbackReports','FeedbackController@getDemoFeedbackReports');
        Route::get('getDemoFeedbackList','FeedbackController@getDemoFeedbackList');
        Route::get('exportFeedbackReport/{fromDate}/{toDate}/{subcat_id}','FeedbackController@exportFeedbackReport');
        
        Route::get('FetchMchPriceList','OrderController@FetchMchPriceList');
        Route::get('FetchAccPriceList','OrderController@FetchAccPriceList');


    //Expense
        Route::get('getExpenseList','TourPlanningController@getExpenseList');
        Route::get('getPendingExpense','TourPlanningController@getPendingExpenseWeb')->name('getPendingExpense');
        Route::get('getExpenseDetails/{transaction_code}','TourPlanningController@getExpenseDetailsWeb');
        Route::post('expenseApprove','TourPlanningController@expenseApproveWeb')->name('expense.approve');
        Route::post('expenseReject','TourPlanningController@expenseRejectWeb')->name('expense.reject');
        Route::get('printExpense/{emp_id}/{token}','TourPlanningController@printExpense');
        Route::get('blockExpense/{emp_id}/{token}','TourPlanningController@blockExpense');
        Route::get('unblockExpense/{emp_id}/{token}','TourPlanningController@unblockExpense');


    //PARTS Routes
        Route::post('updatePartsOrder','OrderController@updatePartsOrder');

    //Common Routes

        //Order Routes
        Route::get('GetAllNotifications','OrderController@GetAllNotifications');
        Route::post('FetchMchGrpList','OrderController@FetchMchGrpList');
        Route::post('ViewOrderDetails','OrderController@ViewOrderDetails');
        Route::post('ChangeItemQtyByExec','OrderController@ChangeItemQtyByExec');

        //Machinery & Accessories Price List
        Route::get('GetMchPriceList','OrderController@GetMchPriceList')->name('order.mch_price_list');
        Route::get('GetAccPriceList','OrderController@GetAccPriceList')->name('order.acc_price_list');

        //Firebase Messaging Token Routes
        Route::post('sendTokenToServer','TestController@sendTokenToServer');
        Route::post('getCurrentUserEmail','TestController@getCurrentUserEmail');
        Route::get('ShowSuccessPage', 'OrderController@ShowSuccessPage')->name('order.success');
        
        //Filters
        Route::get('FilterExePlacedOrders','FilterController@FilterExePlacedOrders');
        Route::get('FilterAllOrdersByMgmt','OrderController@FilterAllOrdersByMgmt');
        Route::get('FilterAllOrdersByExec','OrderController@FilterAllOrdersByExec');
        Route::get('FilterAllByPurchaseNumber','OrderController@FilterAllByPurchaseNumber');
        Route::get('FilterByDealer','OrderController@FilterByDealer');
        Route::get('FilterAllByDealer','OrderController@FilterAllByDealer');
        Route::get('FilterByOrderStatus','OrderController@FilterByOrderStatus');
        Route::get('FilterAllByOrderStatus','OrderController@FilterAllByOrderStatus');
        Route::get('FilterByFromAndToDate','OrderController@FilterByFromAndToDate');
        Route::get('FilterAllByFromAndToDate','OrderController@FilterAllByFromAndToDate');
        Route::get('FilterByGrpName','OrderController@FilterByGrpName');
        Route::get('FilterBySubgrpName','OrderController@FilterBySubgrpName');
        Route::get('FilterBySkuName','OrderController@FilterBySkuName');
        Route::get('FilterByHsn','OrderController@FilterByHsn');
        Route::get('FilterMyRegionOrders','FilterController@FilterMyRegionOrders');
        Route::get('FilterPayApprovedOrders','FilterController@FilterPayApprovedOrders');
        Route::get('FilterPendingPartsOrder','FilterController@FilterPendingPartsOrder');
        Route::get('FilterDealerVisited','FilterController@FilterDealerVisited');
        Route::get('FilterExpenses','FilterController@FilterExpenses');
        Route::get('FilterEmployeeTracking','FilterController@FilterEmployeeTracking');

        //Executive
        Route::post('ViewExecOrderDetails','OrderController@ViewExecOrderDetails');
        Route::post('ChangeOrderStatus','OrderController@ChangeOrderStatus')->name('order.exec_approve');
        Route::post('ViewOrderPdf','OrderController@ViewOrderPdf')->name('order_pdf');
        Route::post('LoadShipMode','OrderController@LoadShipMode');
        Route::post('FetchPriceRate','OrderController@FetchPriceRate');
        Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
        
        Route::get('cart','OrderController@cart')->name('order.cart');
        Route::post('RemoveItemFromCart','OrderController@RemoveItemFromCart');

        //Dispatch Routes
        Route::resource('dispatch', 'DispatchController');
        Route::post('new_dispatch', 'DispatchController@NewDispatch')->name('dispatch.new_dispatch');
        Route::post('GetShippingCompanies', 'OrderController@GetShippingCompanies');

        //Shipping Routes
        Route::resource('shipping', 'ShippingController');

        //Home Routes
        Route::post('FetchDashboardSummary', 'OrderController@FetchDashboardSummary');
        Route::get('AllIndiaOrders','OrderController@Executive__Placed_orders');

        //Notification
        Route::post('GetNotificationCount','OrderController@GetNotificationCount');
        Route::post('ViewDealerOrderDetails','OrderController@ViewDealerOrderDetails');

        Route::get('FetchDistByOneState', 'DealerController@FetchDistByOneState');
        Route::get('FetchDealersByDistricts', 'DealerController@FetchDealersByDistricts');

        Route::resource('dealerVisit', 'DealerVisitController');
        Route::post('RemoveImageFromFolder','DealerVisitController@RemoveImageFromFolder');
        Route::get('/dealerVisits/excel',[
              'as' => 'admin.visit.excel',
              'uses' => 'DealerVisitController@excel'
        ]);
        Route::get('getImageZip','DealerVisitController@zipFile');

        //Employee routes
        Route::resource('employee', 'EmployeeController');
        Route::post('importEmployees', 'EmployeeController@importEmployees')->name('employee.import');
        Route::get('FetchDistByState', 'EmployeeController@FetchDistByState');
});

//Software Developer Routes
Route::group(['middleware' => ['auth','isUserSD']], function () {
        //New Shipping Requests
        Route::get('NewShippingRequest', 'OrderController@GetNewShippingRequest');
        Route::get('NewShippingDetail', 'OrderController@GetNewShippingDetail');
        Route::post('UpdateOrderShipping', 'OrderController@DoUpdateOrderShipping');
        Route::post('KeepNewShipping', 'OrderController@DoKeepNewShipping');


        //Role Routes
        Route::resource('role', 'RoleController');
        Route::get('FilterRole','RoleController@FilterRole');
        
        //Dept Routes
        Route::resource('dept', 'DeptController');
        
        //State Routes
        Route::resource('state', 'StateController');
        
        //Branch Routes
        Route::resource('branch', 'BranchController');
        
        //District Routes
        Route::resource('district', 'DistrictController');
        Route::post('importDistricts', 'DistrictController@importDistricts')->name('district.import');

        //Dealer routes
        Route::resource('dealer', 'DealerController');
        Route::post('importDealers', 'DealerController@importDealers')->name('dealer.import');

        

        //Controller methods for use by dealer
        // Route::get('FilterDealer','DealerController@FilterDealer');

        Route::get('GetDealerOrders', 'OrderController@GetDealerOrders')->name('order.dealer_orders');
        

        //Tax Routes
        Route::resource('tax', 'TaxController');
        
        //Machine Routes
        Route::post('importMachinerySku', 'MachineSkuController@importMachinerySku')->name('machineGroup.import');
        Route::resource('machineSku', 'MachineSkuController');
        
        //Accessory Routes
        Route::post('importAccessories', 'AccessoriesSkuController@importAccessories')->name('accGroup.import');
        Route::resource('accSku', 'AccessoriesSkuController');
});
        //Login routes
        Route::post('CheckUser','TestController@CheckUser');

        //User verification for android
        Route::post('verifyEmail','TestController@verifyEmail');
        Route::post('getAccessToken','TestController@getAccessToken');
        
        Route::get('testMail',function(){
            $data=array('transfer_id'=>'27');
            Mail::to(['dev3.it@kisankraft.com'])->send(new NewStockNotification($data));
	    //mail("dev3.it@kisankraft.com","My subject","TEST");

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{

	protected $hidden = [
        'login_id',
    ];
    
    function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'login_id');
    }

    function branch()
    {
    	return $this->hasOne('App\Models\Branch', 'id', 'branch_id');
    } 

    function dept()
    {
    	return $this->hasOne('App\Models\Dept', 'id', 'dept_id');
    }

    function state()
    {
    	return $this->hasMany('App\Models\EmpState', 'emp_id', 'id');
    } 

    function districts()
    {
        return $this->hasMany(EmpDistrict::class, 'emp_id','id');
    }

    function manager(){
        return $this->hasOne('App\Models\Employee', 'id', 'manager_id');
    }

    function supervisor()
    {
    	return $this->hasOne('App\Models\User', 'id', 'supervisor_id');
    } 

    function email()
    {
        return $this->hasOne('App\Models\Email','id', 'email_id');
    }

    function role()
    {
        return $this->hasOne('App\Models\Role','id','role_id');
    }
}

resources/views/employee/create.blade.php
@extends('layouts.header')
@extends('layouts.content')
@section('content')
<div class="block-header">
    <h2 id="temp">New Employee </h2>
</div>
<div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Fill Employee Details
                            </h2>
                        </div>
                        <div class="body">
                            <form action="{{ route('employee.store') }}" method="post">
                                @csrf
                                <label for="email_address">Email Address</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="email" id="email_address" name="email" class="form-control" placeholder="Enter your email address" required>
                                    </div>
                                </div>
                                <label for="name">Name</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="name" class="form-control" name="name" placeholder="Enter your name">
                                    </div>
                                </div>
                               <label for="supervisor">Supervisor</label>
                                <div class="form-group">
                                  <select  name="supervisor" class="form-control">
                                    @foreach($empList as $emp)
                                      <option value='{{$emp->id}}'>{{$emp->name}}</option>
                                    @endforeach
                                  </select>
                                </div>
                                <label for="mobile">Mobile</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" id="mobile" name="mobile" class="form-control" placeholder="Enter your mobile number">
                                    </div>
                                </div>
                                <label for="address">Address</label>
                                <div class="form-group">
                                        <div class="form-line">
                                            <textarea name="address" rows="4" class="form-control no-resize" placeholder="Type your Address.."></textarea>
                                        </div>
                                </div>

                                  <div class="form-group">
                                    <input type="radio" name="gender" id="male" value="male" class="with-gap">
                                    <label for="male">Male</label>
                                    <input type="radio" name="gender" id="female" value="female" class="with-gap">
                                    <label for="female" class="m-l-20">Female</label>
                                  </div>

                                <label for="roles">Roles</label>
                                <div class="form-group">
                                    <select id="roles" name="role" class="form-control show-tick">
                                         @foreach($roles as $role)
                                          <option value='{{$role->id}}'>{{$role->name}}</option>
                                         @endforeach
                                    </select>
                                </div>
                                <label for="employee">Branch</label>
                                <div class="form-group">
                                  <select  name="branch" class="form-control">
                                    @foreach($branches as $branch)
                                      <option value='{{$branch->id}}'>{{$branch->name}}</option>
                                    @endforeach
                                  </select>
                                </div>
                                <label for="dept">Dept</label>
                                 <div class="form-group">
                                  <select  name="dept" class="form-control">
                                    @foreach($depts as $dept)
                                      <option value='{{$dept->id}}'>{{$dept->name}}</option>
                                    @endforeach
                                  </select>
                                </div>
                                <label for="date_of_join">Date of joining</label>
                                <div class="form-group">
                                        <div class="form-line">
                                            <input type="date" name="date_of_join" id="date_of_join" class="datepicker form-control" placeholder="Please choose a date...">
                                        </div>
                                </div>
                                <label for="state">State</label>
                                 <div class="form-group">
                                  <select  name="state[]" id="state" class="form-control" onchange="FetchDistByState(this.value);" multiple>
                                    @foreach($states as $state)
                                      <option value='{{$state->id}}'>{{$state->name}}</option>
                                    @endforeach
                                  </select>
                                </div>

                                <label for="_districtList" id="lblDistrict">Districts</label>
                                <div class="form-group" id="districtGroup">
                                       <select name="district[]" class="form-control" id = "districts" multiple>
                                             @foreach($districts as $district)
                                              <option value='{{$district->id}}'>{{$district->name}}</option>
                                             @endforeach
                                       </select>
                                </div>

                                <button class="btn btn-blue waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
@endsection
@extends('layouts.footer')
@section('scripts')
<script type="text/javascript">
    function FetchDistByState(stateId)
    {
        var states = $('#state').val();

        $.ajax({
          url: "/FetchDistByState",
          type: 'GET',
          data: {'states': states},
          success: function(jsonData)
          {
             // alert(JSON.stringify(jsonData));
             $('#districtGroup').remove();
             $('#lblDistrict').after('<div class="form-group" id="districtGroup"><select name="districts[]" class="form-control" id = "districts" multiple></select></div>');
             for(var i=0;i<jsonData.length;i++){
                $.each(jsonData[i], function (i, item) {
                $('#districts').append($('<option>', { 
                    value: item.id,
                    text : item.name 
                }));
             });
             }
          },
          error: function (xhr, ajaxOptions, thrownError) 
          {
             alert(xhr.status);
             alert(thrownError);
          }
        });
    }

</script>
  
@endSection

resources/views/employee/index.blade.php
@extends('layouts.header')

@extends('layouts.content')

@section('content')



<style type="text/css">

    .btn

    {

        margin-right: 10px;

    }

</style>

    

<div class="block-header row  clearfix">

                <h2 class="col-lg-10 col-md-10" >Employee </h2>

                <a href='{{ route('employee.create') }}'>

                    <button type="button" class="col-lg-1 col-md-1 btn btn-default waves-effect">

                        <i class="material-icons">add</i>

                        <span>New</span>

                    </button>

                </a>

                <button type="button" id="btnImport" class="btn bg-teal waves-effect">

                    <i class="material-icons">publish</i>

                </button>

            </div>

            

            <div class="row clearfix">

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">



                    <div class="card">

                        <div class="header">

                            <h2>

                                Employee Information 

                            </h2>

                        </div>

                         @if(session()->has('result'))

                         <div class="alert {{Session::get('color')}} alert-dismissible" role="alert">

                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                                {{ Session::get('result') }}

                         </div>

                         @endif

                        <div class="body">

                            <div class="row">

                                <div class="col-sm-6">

                                    <span>Show &nbsp</span>

                                    <select id="pagination" class="">

                                        <option value="">-- Please select --</option>

                                        <option value="5" @if($items == 5) selected @endif >5</option>

                                        <option value="10" @if($items == 10) selected @endif >10</option>

                                        <option value="25" @if($items == 25) selected @endif >25</option>

                                    </select>

                                    <span>&nbsp  rows</span>

                                </div>

                                <div class="col-sm-3">

                                </div>

                                <div class="col-sm-3">

                                     <div class="form-group form-float">

                                        <div class="form-line">

                                            <input type="text" id="_search" class="form-control">

                                            <label class="form-label">Search Employee</label>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                        <div class="body">

                            <div class="table-responsive">

                                <table id="_table" class="table table-bordered table-striped table-hover js-basic-example">

                                    <thead>

                                        <tr>

                                            <th>Name</th>

                                            <th>Dept</th>

                                            <th>Branch</th>

                                            <th>Role</th>

                                            <th>Joined Date</th>

                                            <th width="40">Edit</th>

                                            <th width="40">Delete</th>

                                        </tr>

                                    </thead>

                                    <tbody>

                                        @foreach($employees as $employee)

                                            <tr>

                                                <td>

                                                    {{$employee->name}}

                                                </td>

                                                <td>{{$employee->dept['name']}}</td>

                                                <td>{{$employee->branch->name}}</td>

                                                <td>

                                                    {{$employee->role->name}}

                                                </td>

                                                <td>{{date('d-m-Y', strtotime($employee->date_of_join))}}</td>

                                                <td>

                                                    <form action="{{ route('employee.edit',$employee->id) }}" method="get">

                                                        <button type="submit" class="btn btn-default"><i class="col-grey material-icons">edit</i></button>

                                                    </form>

                                                </td>

                                                <td>

                                                    <form action="{{ route('employee.destroy',$employee->id) }}" method="post">

                                                        @csrf

                                                        @method('DELETE')
                                                        <input type="hidden" name="empId" value="{{$employee->id}}">

                                                        <button type="submit" class="btn btn-default"><i class="col-red material-icons">delete</i></button>

                                                    </form>

                                                </td>

                                            </tr>

                                        @endforeach

                                    </tbody>

                                </table>



                                {{ $employees->links() }}

                            </div>

                        </div>

                    </div>

                </div>

            </div>  

            <div class="modal fade" id="mdModal" tabindex="-1" role="dialog">

                <div class="modal-dialog" role="document">

                    <div class="modal-content">

                        <div class="modal-header">

                            <h3 class="modal-title" id="defaultModalLabel">Upload Employees</h3>

                        </div>

                        <div class="modal-body">

                            <p>Import Excel Data ?</p>

                        </div>

                        <div class="modal-footer">

                            <form action="{{ route('employee.import') }}" method="post" enctype="multipart/form-data">

                                @csrf

                                <input type="file" name="empExcel">

                                <button type="submit" class="btn btn-link waves-effect">Yes</button>

                                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Cancel</button>

                            </form>

                        </div>

                    </div>

                </div>

            </div>   



@endsection

@extends('layouts.footer')



@section('scripts')



<script type="text/javascript">

    

    $(document).ready(function(){



        $('#pagination').change(function(){

            window.location = "{{ $employees->url(1) }}&items=" + this.value;

        })

        

        $('#_search').keyup(function(){

            $.ajax({

            headers: {

                     'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

                 },    

            url: "/FilterEmployee",

            type: 'GET',

            data: {'queryFilter':this.value},

            success: function(jsonData)

            {

                // alert(JSON.stringify(jsonData));

               $("#_table tbody tr").remove();

               for(var i=0;i<jsonData.data.length;i++)

               {

                    var employeeId = jsonData.data[i].id;



                    var eBtn = '<form action="{{ route('employee.edit','+employeeId+') }}" method="get"><button type="submit" class="btn btn-default"><i class="col-grey material-icons">edit</i></button></form>';



                    var dBtn = '<form action="{{ route('employee.destroy','+employeeId+') }}" method="post"> @csrf @method('PUT') <button type="submit" class="btn btn-default"><i class="col-red material-icons">delete</i></button></form>'



                    var date = new Date(jsonData.data[i].date_of_join);

                    var supervisor = null;

                    if(jsonData.data[i]['supervisor'] != null)

                        supervisor = jsonData.data[i]['supervisor']['name'];

                    var row = $("<tr><td>"+jsonData.data[i]['user']['name']+"</td><td>"+supervisor+"</td><td>"+jsonData.data[i]['dept']['name']+"</td><td>"+jsonData.data[i]['branch']['name']+"</td><td>"+jsonData.data[i]['role']['name']+"</td><td>"+(date.getMonth() + 1) + '-' + date.getDate() + '-' +  date.getFullYear()+"</td><td>"+eBtn+"</td><td>"+dBtn+"</td><tr>");

                    $("#_table").append(row);

               }

            },

            error: function (xhr, ajaxOptions, thrownError) 

            {

               alert(xhr.status);

               alert(thrownError);

            }

            });      

        })

    });



    $(function () {

        $('#btnImport').on('click', function () {

            var color = $(this).data('color');

            $('#mdModal .modal-content').removeAttr('class').addClass('modal-content modal-col-teal');

            $('#mdModal').modal('show');

        });

    });

     

</script>   

  

@endSection