routes/web.php
        Route::get('tourDelete/{emp_id}/{token}/{action}','TourPlanningController@tourDelete');
        Route::get('tourDetails/{emp_id}/{token}','TourPlanningController@tourDetails');
        Route::post('tourApprove','TourPlanningController@tourApprove')->name('tour.approve');
        Route::post('tourReject','TourPlanningController@tourReject')->name('tour.reject');
        Route::post('tourUpdate','TourPlanningController@tourUpdate')->name('tour.update');
        Route::get('tourEdit/{tour_id}','TourPlanningController@tourEdit');

    //Demo Plan
        Route::get('getWebPendingDemoList','DemoPlanController@getWebPendingDemoList')->name('pendingDemo');
        Route::get('pendingDemoDetails/{emp_id}/{token}','DemoPlanController@pendingDemoDetails');
        Route::get('getAllDemoDetails/{emp_id}/{token}','DemoPlanController@getAllDemoDetails');
        Route::post('demoApprove','DemoPlanController@demoApprove')->name('demo.approve');
        Route::post('demoReject','DemoPlanController@demoReject')->name('demo.reject');
        Route::get('approvedDemo','DemoPlanController@getWebApprovedDemoList')->name('approvedDemos');
        Route::get('demoPrint/{emp_id}/{token}','DemoPlanController@demoPrint');
        Route::get('demoPlanExcel/{emp_id}/{token}','DemoPlanController@excel');

    //Feedback Reports
        Route::get('getDemoFeedbackReports','FeedbackController@getDemoFeedbackReports');
        Route::get('getDemoFeedbackList','FeedbackController@getDemoFeedbackList');
        Route::get('exportFeedbackReport/{fromDate}/{toDate}/{subcat_id}','FeedbackController@exportFeedbackReport');
        
        Route::get('FetchMchPriceList','OrderController@FetchMchPriceList');
        Route::get('FetchAccPriceList','OrderController@FetchAccPriceList');


    //Expense
        Route::get('getExpenseList','TourPlanningController@getExpenseList');
        Route::get('getPendingExpense','TourPlanningController@getPendingExpenseWeb')->name('getPendingExpense');
        Route::get('getExpenseDetails/{transaction_code}','TourPlanningController@getExpenseDetailsWeb');
        Route::post('expenseApprove','TourPlanningController@expenseApproveWeb')->name('expense.approve');
        Route::post('expenseReject','TourPlanningController@expenseRejectWeb')->name('expense.reject');
        Route::get('printExpense/{emp_id}/{token}','TourPlanningController@printExpense');
        Route::get('blockExpense/{emp_id}/{token}','TourPlanningController@blockExpense');
        Route::get('unblockExpense/{emp_id}/{token}','TourPlanningController@unblockExpense');


    //PARTS Routes
        Route::post('updatePartsOrder','OrderController@updatePartsOrder');

    //Common Routes

        //Order Routes
        Route::get('GetAllNotifications','OrderController@GetAllNotifications');
        Route::post('FetchMchGrpList','OrderController@FetchMchGrpList');
        Route::post('ViewOrderDetails','OrderController@ViewOrderDetails');
        Route::post('ChangeItemQtyByExec','OrderController@ChangeItemQtyByExec');

        //Machinery & Accessories Price List
        Route::get('GetMchPriceList','OrderController@GetMchPriceList')->name('order.mch_price_list');
        Route::get('GetAccPriceList','OrderController@GetAccPriceList')->name('order.acc_price_list');

        //Firebase Messaging Token Routes
        Route::post('sendTokenToServer','TestController@sendTokenToServer');
        Route::post('getCurrentUserEmail','TestController@getCurrentUserEmail');
        Route::get('ShowSuccessPage', 'OrderController@ShowSuccessPage')->name('order.success');
        
        //Filters
        Route::get('FilterExePlacedOrders','FilterController@FilterExePlacedOrders');
        Route::get('FilterAllOrdersByMgmt','OrderController@FilterAllOrdersByMgmt');
        Route::get('FilterAllOrdersByExec','OrderController@FilterAllOrdersByExec');
        Route::get('FilterAllByPurchaseNumber','OrderController@FilterAllByPurchaseNumber');
        Route::get('FilterByDealer','OrderController@FilterByDealer');
        Route::get('FilterAllByDealer','OrderController@FilterAllByDealer');
        Route::get('FilterByOrderStatus','OrderController@FilterByOrderStatus');
        Route::get('FilterAllByOrderStatus','OrderController@FilterAllByOrderStatus');
        Route::get('FilterByFromAndToDate','OrderController@FilterByFromAndToDate');
        Route::get('FilterAllByFromAndToDate','OrderController@FilterAllByFromAndToDate');
        Route::get('FilterByGrpName','OrderController@FilterByGrpName');
        Route::get('FilterBySubgrpName','OrderController@FilterBySubgrpName');
        Route::get('FilterBySkuName','OrderController@FilterBySkuName');
        Route::get('FilterByHsn','OrderController@FilterByHsn');
        Route::get('FilterMyRegionOrders','FilterController@FilterMyRegionOrders');
        Route::get('FilterPayApprovedOrders','FilterController@FilterPayApprovedOrders');
        Route::get('FilterPendingPartsOrder','FilterController@FilterPendingPartsOrder');
        Route::get('FilterDealerVisited','FilterController@FilterDealerVisited');
        Route::get('FilterExpenses','FilterController@FilterExpenses');
        Route::get('FilterEmployeeTracking','FilterController@FilterEmployeeTracking');

        //Executive
        Route::post('ViewExecOrderDetails','OrderController@ViewExecOrderDetails');
        Route::post('ChangeOrderStatus','OrderController@ChangeOrderStatus')->name('order.exec_approve');
        Route::post('ViewOrderPdf','OrderController@ViewOrderPdf')->name('order_pdf');
        Route::post('LoadShipMode','OrderController@LoadShipMode');
        Route::post('FetchPriceRate','OrderController@FetchPriceRate');
        Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
        
        Route::get('cart','OrderController@cart')->name('order.cart');
        Route::post('RemoveItemFromCart','OrderController@RemoveItemFromCart');

        //Dispatch Routes
        Route::resource('dispatch', 'DispatchController');
        Route::post('new_dispatch', 'DispatchController@NewDispatch')->name('dispatch.new_dispatch');
        Route::post('GetShippingCompanies', 'OrderController@GetShippingCompanies');

        //Shipping Routes
        Route::resource('shipping', 'ShippingController');

        //Home Routes
        Route::post('FetchDashboardSummary', 'OrderController@FetchDashboardSummary');
        Route::get('AllIndiaOrders','OrderController@Executive__Placed_orders');

        //Notification
        Route::post('GetNotificationCount','OrderController@GetNotificationCount');
        Route::post('ViewDealerOrderDetails','OrderController@ViewDealerOrderDetails');

        Route::get('FetchDistByOneState', 'DealerController@FetchDistByOneState');
        Route::get('FetchDealersByDistricts', 'DealerController@FetchDealersByDistricts');

        Route::resource('dealerVisit', 'DealerVisitController');
        Route::post('RemoveImageFromFolder','DealerVisitController@RemoveImageFromFolder');
        Route::get('/dealerVisits/excel',[
              'as' => 'admin.visit.excel',
              'uses' => 'DealerVisitController@excel'
        ]);
        Route::get('getImageZip','DealerVisitController@zipFile');

        //Employee routes
        Route::resource('employee', 'EmployeeController');
        Route::post('importEmployees', 'EmployeeController@importEmployees')->name('employee.import');
        Route::get('FetchDistByState', 'EmployeeController@FetchDistByState');
});

//Software Developer Routes
Route::group(['middleware' => ['auth','isUserSD']], function () {
        //New Shipping Requests
        Route::get('NewShippingRequest', 'OrderController@GetNewShippingRequest');
        Route::get('NewShippingDetail', 'OrderController@GetNewShippingDetail');
        Route::post('UpdateOrderShipping', 'OrderController@DoUpdateOrderShipping');
        Route::post('KeepNewShipping', 'OrderController@DoKeepNewShipping');


        //Role Routes
        Route::resource('role', 'RoleController');
        Route::get('FilterRole','RoleController@FilterRole');
        
        //Dept Routes
        Route::resource('dept', 'DeptController');
        
        //State Routes
        Route::resource('state', 'StateController');
        
        //Branch Routes
        Route::resource('branch', 'BranchController');
        
        //District Routes
        Route::resource('district', 'DistrictController');
        Route::post('importDistricts', 'DistrictController@importDistricts')->name('district.import');

        //Dealer routes
        Route::resource('dealer', 'DealerController');
        Route::post('importDealers', 'DealerController@importDealers')->name('dealer.import');

        

        //Controller methods for use by dealer
        // Route::get('FilterDealer','DealerController@FilterDealer');

        Route::get('GetDealerOrders', 'OrderController@GetDealerOrders')->name('order.dealer_orders');
        

        //Tax Routes
        Route::resource('tax', 'TaxController');
        
        //Machine Routes
        Route::post('importMachinerySku', 'MachineSkuController@importMachinerySku')->name('machineGroup.import');
        Route::resource('machineSku', 'MachineSkuController');
        
        //Accessory Routes
        Route::post('importAccessories', 'AccessoriesSkuController@importAccessories')->name('accGroup.import');
        Route::resource('accSku', 'AccessoriesSkuController');
});
        //Login routes
        Route::post('CheckUser','TestController@CheckUser');

        //User verification for android
        Route::post('verifyEmail','TestController@verifyEmail');
        Route::post('getAccessToken','TestController@getAccessToken');
        
        Route::get('testMail',function(){
            $data=array('transfer_id'=>'27');
            Mail::to(['dev3.it@kisankraft.com'])->send(new NewStockNotification($data));
	    //mail("dev3.it@kisankraft.com","My subject","TEST");

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use Illuminate\Http\Request;
use Session;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $items = $request->items ?? 5;
        $roles = Role::where('status','=',1)->paginate($items);
        return view('role.index')->with(compact('roles','items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('role.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            $role = new Role();
            $role->name = $request->name;
            $role->code = $request->code;
            $role->save();
            return redirect()->route("role.index")->with(['result'=>'New role added','color'=>'bg-green']);
        }
        catch(\Exception $e){
           // do task when error
            return redirect()->route("role.index")->with(['result'=>'Error adding role','color'=>'alert-warning']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
          $role = Role::find($role->id);
          return view('role.edit')->with(compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        try{
         $role = Role::find($role->id);
         $role->name = $request->name;
         $role->code = $request->code;
         $role->save();
         return redirect()->route('role.index')->with(['result'=>'Role update successfully','color'=>'bg-green']);
         }
        catch(\Exception $e){
           // do task when error
            return redirect()->route("role.index")->with(['result'=>'Error updating role','color'=>'alert-warning']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $roles = Role::find($role->id);
        $roles->status = 0;
        $roles->save();
        return redirect()->route('role.index')->with(['result'=>'Role deleted successfully','color'=>'bg-green']);
    }

    public function FilterRole()
    {
        $query = $_GET['queryFilter'];
        $roles = Role::where('name', 'LIKE', '%' . $query . '%')->where('status','=',1)->paginate(5);
        return $roles;
    }
}

resources/views/role/create.blade.php
@extends('layouts.header')
@extends('layouts.content')
@section('content')
<div class="block-header">
	<h2 id="temp">New Role </h2>
</div>
<div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Fill Role Details
                            </h2>
                        </div>
                        <div class="body">
                            <form action="{{ route('role.store') }}" method="post">
                            	@csrf
                                <label for="name">Name</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="name" id="_name" class="form-control" placeholder="Enter role name">
                                    </div>
                                </div>
                                <label for="code">Code</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="code" id="_code" class="form-control" placeholder="Enter role code">
                                    </div>
                                </div>

                                <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
@endsection
@extends('layouts.footer')

@section('scripts')
	
@endSection

resources/views/role/edit.blade.php
@extends('layouts.header')
@extends('layouts.content')
@section('content')
<div class="block-header">
	<h2 id="temp">New Role </h2>
</div>
<div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Update Role Details
                            </h2>
                        </div>
                        <div class="body">
                            <form action="{{ route('role.update',$role->id) }}" method="post">
                            	@csrf
                                @method('PUT')
                                <label for="name">Name</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="name" id="_name" value="{{$role->name}}" class="form-control" placeholder="Enter role name">
                                    </div>
                                </div>
                                <label for="code">Code</label>
                                <div class="form-group">
                                    <div class="form-line">
                                        <input type="text" name="code" id="_code" value="{{$role->code}}" class="form-control" placeholder="Enter role code">
                                    </div>
                                </div>

                                <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
@endsection

@extends('layouts.footer')

resources/views/role/index.blade.php
@extends('layouts.header')
@extends('layouts.content')
@section('content')

<style type="text/css">
    .btn
    {
        margin-right: 10px;
    }
</style>

<div class="block-header row  clearfix">
                <h2 class="col-lg-10 col-md-10" >Roles </h2>
                <a href='{{ route('role.create') }}'>
                    <button type="button" class="col-lg-1 col-md-1 btn btn-default waves-effect">
                        <i class="material-icons">add</i>
                        <span>New</span>
                    </button>
                </a>
                <button type="button" class="btn bg-teal waves-effect">
                    <i class="material-icons">publish</i>
                </button>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                    <div class="card">
                        <div class="header">
                            <h2>
                                Role Information 
                            </h2>
                        </div>
                         @if(session()->has('result'))
                         <div class="alert {{Session::get('color')}} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                {{ Session::get('result') }}
                         </div>
                         @endif
                        <div class="body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <span>Show &nbsp</span>
                                    <select id="pagination" class="">
                                        <option value="">-- Please select --</option>
                                        <option value="5" @if($items == 5) selected @endif >5</option>
                                        <option value="10" @if($items == 10) selected @endif >10</option>
                                        <option value="25" @if($items == 25) selected @endif >25</option>
                                    </select>
                                    <span>&nbsp  rows</span>
                                </div>
                                <div class="col-sm-3">
                                </div>
                                <div class="col-sm-3">
                                     <div class="form-group form-float">
                                        <div class="form-line">
                                            <input type="text" id="_search" class="form-control">
                                            <label class="form-label">Search Role</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table id="_tblRole" class="table table-bordered table-striped table-hover js-basic-example">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th width="40">Edit</th>
                                            <th width="40">Delete</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($roles as $role)
                                            <tr>
                                                <td>{{$role->name}}</td>
                                                <td>
                                                    <form action="{{ route('role.edit',$role->id) }}" method="get">
                                                        <button type="submit" class="btn btn-default"><i class="col-grey material-icons">edit</i></button>
                                                    </form>
                                                </td>
                                                <td>
                                                    <form action="{{ route('role.destroy',$role->id) }}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-default"><i class="col-red material-icons">delete</i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>

                                {{ $roles->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
@endsection
@extends('layouts.footer')
@section('scripts')

<script type="text/javascript">
    
    $(document).ready(function(){

        $('#pagination').change(function(){
            window.location = "{{ $roles->url(1) }}&items=" + this.value;
        })
        
        $('#_search').keyup(function(){
            $.ajax({
            url: "/FilterRole",
            type: 'GET',
            data: {'queryFilter':this.value},
            success: function(jsonData)
            {
                // alert(JSON.stringify(jsonData));
               $("#_tblRole tbody tr").remove();
               for(var i=0;i<jsonData.data.length;i++)
               {
                    var roleId = jsonData.data[i].id;

                    var eBtn = '<form action="{{ route('role.edit','+roleId+') }}" method="get"><button type="submit" class="btn btn-default"><i class="col-grey material-icons">edit</i></button></form>';

                    var dBtn = '<form action="{{ route('role.destroy','+roleId+') }}" method="post"> @csrf @method('PUT') <button type="submit" class="btn btn-default"><i class="col-red material-icons">delete</i></button></form>'

                    var row = $("<tr><td>"+jsonData.data[i].name+"</td><td>"+eBtn+"</td><td>"+dBtn+"</td><tr>");
                    $("#_tblRole").append(row);
               }
            },
            error: function (xhr, ajaxOptions, thrownError) 
            {
               alert(xhr.status);
               alert(thrownError);
            }
            });      
        })
    })
    
</script>   
  
@endSection